# constants/json_type_constants.py

CONFIGURATION = "Configuration"
PRODUCTION_COUNT = "ProductionCount"
PRODUCTION_ORDER = "ProductionOrder"
PRODUCTION_ORDER_RESPONSE = "ProductionOrderResponse"
PRODUCTION_ORDER_CONCLUSION = "ProductionOrderConclusion"
PRODUCTION_ORDER_CONCLUSION_RESPONSE = "ProductionOrderConclusionResponse"

ALL_JSON_TYPES = [
    CONFIGURATION,
    PRODUCTION_COUNT,
    PRODUCTION_ORDER,
    PRODUCTION_ORDER_RESPONSE,
    PRODUCTION_ORDER_CONCLUSION,
    PRODUCTION_ORDER_CONCLUSION_RESPONSE,
]
